# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

[project]
name = "lfx-v1-sync-helper"
version = "0.1.0"
description = "LFX v1<>v2 data sync components"
requires-python = ">=3.12,<3.13"
dependencies = [
    "meltano==4.0.3",
]
